### ISSUE TITLE
Remove deasync

### ISSUE THREAD

**Issue by HarleyKwyn** [IndicoDataSolutions/IndicoIo-node#19]
In general this module needs to be restructured and bumped a version to work asynchronously. Potentially with promises to make it more manageable.

**Comment by madisonmay** [comment]
:+1: -- we'd very much appreciate a pull request to clean that up.  Deasync was a bit of a hack to retrofit some additions into some pre-existing code.

**Comment by HarleyKwyn** [comment]
Sweet. Will work on it.

**Comment by madisonmay** [comment]
Maybe this in place of the image API revamp?

**Comment by HarleyKwyn** [comment]
Haha, if that would help. Then yes. It would actually make the image
loading revamp much easier.

**Comment by HarleyKwyn** [comment]
Fixed by #23
